- namespace: testingOverrides
  description: Accesses additional preferences used for study testing

  functions:
  - name: getModelUrlEndpointOverride
    type: 'function'
    async: true
    description: ''
    parameters: []
  - name: getSurveyDaysFromExpirationOverride
    type: 'function'
    async: true
    description: ''
    parameters: []
