- namespace: experiments.awesomeBar
  description: Listen to awesome bar interactions

  types:
  - id: awesomeBarState
    $schema: "http://json-schema.org/draft-04/schema"
    type: object
    properties:
      rankSelected:
        type: number
      searchString:
        type: string
      searchStringLength:
        type: number
      numSuggestionsDisplayed:
        type: number
      suggestions:
        type: array
        items:
          type: string
    required: ["rankSelected", "searchString", "searchStringLength", "numSuggestionsDisplayed", "suggestions"]
    testcase: {rankSelected: 2, searchString: "foo", searchStringLength: 3, numSuggestionsDisplayed: 11, suggestions: []}
  - id: keyEvent
    $schema: "http://json-schema.org/draft-04/schema"
    type: object
    properties:
      charCode:
        type: number
      keyCode:
        type: number
      key:
        type: string
      altKey:
        type: boolean
      shiftKey:
        type: boolean
      ctrlKey:
        type: boolean
      metaKey:
        type: boolean
    required: ["charCode", "keyCode", "key", "altKey", "shiftKey", "ctrlKey", "metaKey"]
    testcase: {altKey: false, charCode: 0, ctrlKey: false, key: "Enter", keyCode: 13, metaKey: false, shiftKey: false}

  functions:
  - name: start
    type: function
    async: true
    description: Start listening to awesome bar interactions
    parameters: []
  - name: stop
    type: function
    async: true
    description: Stop listening to awesome bar interactions
    parameters: []

  events:
  - name: onAutocompleteSuggestionSelected
    type: function
    description: Fires when a suggestion has been suggested in the awesome bar autocomplete popup.
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onFocus
    type: function
    description: Enter the awesome bar
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onBlur
    type: function
    description: Exit the awesome bar
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onInput
    type: function
    description: Character typed/deleted
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onAutocompleteSuggestionsHidden
    type: function
    description: Fires when autocomplete popup has been cancelled by some means, like pressing escape
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onAutocompleteSuggestionsUpdated
    type: function
    description: Autocomplete suggestions changed
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onKeyDown
    type: function
    description: Fires when a key is pressed down in the awesome bar (including meta/modifier keys). May repeat if key is held down.
    parameters:  # for the callback
    - name: keyEvent
      $ref: keyEvent
  - name: onKeyPress
    type: function
    description: Fires after one or a combination of keys has been pressed and lead to an input into the awesome bar (without information about which meta/modifier key was used). May repeat if key is held down.
    parameters:  # for the callback
    - name: keyEvent
      $ref: keyEvent
